### ISSUE TITLE
Task9

### ISSUE THREAD

**Issue by AntonZamyatin** [AntonZamyatin/bio-python-course#5]
Solved

**Comment by YakutovDmitriy** [comment]
* You use this kind of expression: `os.path.split(self.path)[0] + '\\' + newname`. Please read about `os.path.join`, it can correctly concatenate pairs of paths like `('~/dir', 'b.txt')`, `('~/dir/', 'b.txt')`, `('~/dir/', '/b.txt')` and it works on any OS.

* `FSItem.rename`. It doesn't move current file or directory in actual OS
* `FSItem.create`. It uses `item_type` variable here to decide what to do. This problem can be solved using inheritance: `File.create` must create file and `Directory.create` must create directory

* `File.getcontent`. Using `str.strip` here removes all leading and trailing spaces in every line. This behaviour is not expected, but it is not great problem
* `File.__iter__`. You decided to make current object iterator on current object. This is not good idea because now you can't create two or more iterators on current object. I expected you to use `getcontent` here or create separate class `FileIterator`

* `Directory.items`. It was not expected to create instances of `FSItem` directly. You have to create `File` or `Directory` instance because you can decide which one to create. Otherwise it is impossible to use methods `items`, `getcontent` and other special methods of these `FSItem` types

* `Directory.filesrecursive`. Now you yield files inside of current directory and files inside of its subdirectories, not deeper. I guess its just a bug, please fix it
* `Directory.getsubdirectory`. I expected a bit other behaviour, but this one is ok too. I wanted you to raise error only if `name` exists and `name` is file. It means that it is absolutely incorrect to create directory with name `name`. Now this piece of code can't be executed:
```python
d = Directory('~/dir/')
sd = d.getsubdirectory('subdir') # unexisting subdirectory
sd.create()
```

**Comment by AntonZamyatin** [comment]
Fixed

**Comment by YakutovDmitriy** [comment]
I want you to fix the first point. Other tips are up to you

* `FSItem.create`. You still doesn't use inheritance (and polymorphism). If you don't understand what I mean you can ask me vie telegram or read [this example](https://en.wikipedia.org/wiki/Polymorphism_(computer_science)#Subtyping)
* `File.__iter__`. This is ok, but the same could be done with this:
  ```python
  def __iter__(self):
      return iter(self.getcontent())
  ```
* `Direcrory.items`. It's ok. But good programmer won't write code like this. There is too much copy-paste expressions (`os.path.join(self.path, name)`). It is good practice to create variables for expressions you use several times
* `Directory.files` and `Directory.subdirectories`. This works too. But it is possible to write less repeating code. There are two ways:
    * Implement `items` using `files` and `subdirectories`:
        ```python
        def items(self):
            yield from self.files()
            yield from self.subdirectories()
        ````
    * Implement `files` and `subdirectories` using `items`:
        ```python
        def files(self):
            yield from filter(lambda x: x.isfile(), self.items())
        def subdirectoies(self):
            yield from filter(lambda x: x.isdirectory(), self.items())
        ````
    The first way is better because in the second way we create directories even if we need only files. So we can spend a lot of memory if we have only several files and hundreds of directories in current directory

**Comment by AntonZamyatin** [comment]
fixed exept `File.__iter__ `but I understand thanks.

**Comment by YakutovDmitriy** [comment]
Ok, good
